# bundle exec jekyll serve --host=0.0.0.0

title: MycilaEasyDisplay
description: Easy to use Arduino / ESP32 library for SH1106, SH1107, SSD1306 OLED I2C displays
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
